name: Bash Script CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      users: actions/checkout@v3
      
    - name: Run syntax check
      run:  bash -n main.sh 
